develop:
  extends:
    file: base.yml
    service: base
  container_name: gfw-prodes-loss-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:3600
    API_VERSION: v1
    CT_REGISTER_MODE: auto
  command: develop
  volumes:
    - ./app:/opt/gfw-prodes-loss-api/app
