version: "3"
services:
  develop:
    build: .
    ports:
      - "3600:3600"
    container_name: gfw-prodes-loss-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-01
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3600
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: develop
    volumes:
      - ./app:/opt/gfw-prodes-loss-api/app
