version: "3"
services:
  develop:
    build: .
    ports:
      - "3600:3600"
    container_name: gfw-prodes-loss-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-01
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3600
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/gfw-prodes-loss-api/app
