version: "3"
services:
  develop:
    build: .
    ports:
      - "3602:3602"
    container_name: gfw-prodes-loss-api-develop
    environment:
      PORT: 3602
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-01
      CT_URL: http://mymachine:9000
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      LOCAL_URL: http://mymachine:3602
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/gfw-prodes-loss-api/app
